-- Adicionar colunas para autenticação social na tabela USUARIOS
ALTER TABLE USUARIOS 
ADD COLUMN GOOGLE_ID VARCHAR(255) NULL,
ADD COLUMN INSTAGRAM_ID VARCHAR(255) NULL,
ADD COLUMN USER_USUARIO VARCHAR(100) NULL,
ADD COLUMN EMAIL_USUARIO VARCHAR(100) NULL;

-- Criar índices para melhor performance
CREATE INDEX idx_google_id ON USUARIOS(GOOGLE_ID);
CREATE INDEX idx_instagram_id ON USUARIOS(INSTAGRAM_ID);
CREATE INDEX idx_user_usuario ON USUARIOS(USER_USUARIO);
CREATE INDEX idx_email_usuario ON USUARIOS(EMAIL_USUARIO);

-- Permitir que a senha seja NULL para usuários de login social
ALTER TABLE USUARIOS MODIFY COLUMN SENHA_USUARIO VARCHAR(255) NULL;