CREATE DATABASE VINTELO;

USE VINTELO;

CREATE TABLE USUARIOS (
    ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    NOME_USUARIO VARCHAR(70) NOT NULL,
    CELULAR_USUARIO CHAR(11) UNIQUE NOT NULL,
    EMAIL_USUARIO VARCHAR(35) UNIQUE NOT NULL,
    DT_NASC_USUARIO DATE NOT NULL,
    LOGRADOURO_USUARIO VARCHAR(100) NOT NULL,
    BAIRRO_USUARIO VARCHAR(30) NOT NULL,
    CIDADE_USUARIO VARCHAR(30) NOT NULL,
    UF_USUARIO CHAR(2) NOT NULL,
    CEP_USUARIO CHAR(8) NOT NULL,
    SENHA_USUARIO CHAR(6) NOT NULL
    );
    
CREATE TABLE CLIENTES (
    ID_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    CPF_CLIENTE CHAR(11) UNIQUE NOT NULL,
    ID_USUARIO INT NOT NULL,
    FOREIGN KEY (id_usuario) REFERENCES USUARIOS(id_usuario)
    );
    
CREATE TABLE BRECHOS (
    ID_BRECHO INT PRIMARY KEY AUTO_INCREMENT,
    CNPJ_BRECHO CHAR(14) UNIQUE NOT NULL,
    ID_USUARIO INT NOT NULL,
    RAZÃO_SOCIAl VARCHAR(100) NOT NULL,
    NOME_FANTASIA VARCHAR(100) NOT NULL,
    FOREIGN KEY (id_usuario) REFERENCES USUARIOS(id_usuario)
    );
    
CREATE TABLE ADMINISTRADORES (
    ID_ADM INT PRIMARY KEY AUTO_INCREMENT,
    SENHA_ADM CHAR(11) NOT NULL,
    USUARIO_ADM INT NOT NULL,
    FOREIGN KEY (id_usuario) REFERENCES USUARIOS(id_usuario)
    );

CREATE TABLE PERFIS (
    ID_PERFIL INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT NOT NULL,
    IMG BLOB,
    FOREIGN KEY (id_usuario) REFERENCES USUARIOS(id_usuario)
    );
    
CREATE TABLE PRODUTOS_BRECHOS (
    ID_PROD_BRECHO INT PRIMARY KEY AUTO_INCREMENT,
    NOME_PROD_BRECHO VARCHAR(100) NOT NULL,
    DESCRICAO_PROD_BRECHO VARCHAR(150) NOT NULL,
    PRECO DECIMAL(10, 2) NOT NULL,
    TIPO_PECA VARCHAR(50) NOT NULL,
    TAMANHO CHAR(2),
    DATA_CADASTRO DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_brecho) REFERENCES BRECHOS(id_brecho)
    );
    
    CREATE TABLE PRODUTOS_CLIENTES (
    ID_PROD_CLIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME_PROD_CLIENTE VARCHAR(100) NOT NULL,
    DESCRICAO_PROD_CLIENTE VARCHAR(150) NOT NULL,
    PRECO DECIMAL(10, 2) NOT NULL,
    TIPO_PECA VARCHAR(50) NOT NULL,
    TAMANHO CHAR(10),
    DATA_CADASTRO DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (id_cliente) REFERENCES CLIENTES(id_cliente)
    );
    
CREATE TABLE PEDIDOS_BRECHOS (
    ID_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
    ID_PROD_BRECHO INT NOT NULL,
    ID_CLIENTE INT NOT NULL,
    ID_BRECHO INT NOT NULL,
    QUANTIDADE INT DEFAULT 1,
    DATA_PEDIDO DATETIME DEFAULT CURRENT_TIMESTAMP,
    STATUS_PEDIDO ENUM('pendente', 'pago', 'enviado', 'concluido') DEFAULT 'pendente',
    CODIGO_RASTREIO CHAR(13),
    VALOR_TOTAL DECIMAL(10, 2) NOT NULL,
FOREIGN KEY (id_prod_brecho) REFERENCES PRODUTOS_BRECHOS(id_prod_brecho),
FOREIGN KEY (id_cliente) REFERENCES CLIENTES(id_cliente),
FOREIGN KEY (id_brecho) REFERENCES BRECHOS(id_brecho)
);

CREATE TABLE PEDIDOS_CLIENTES (
    ID_PEDIDO INT PRIMARY KEY AUTO_INCREMENT,
    ID_PROD_CLIENTE INT NOT NULL,
    ID_CLIENTE INT NOT NULL,
    QUANTIDADE INT DEFAULT 1,
    DATA_PEDIDO DATETIME DEFAULT CURRENT_TIMESTAMP,
    STATUS_PEDIDO ENUM('pendente', 'pago', 'enviado', 'concluido') DEFAULT 'pendente',
    CODIGO_RASTREIO CHAR(13),
    VALOR_TOTAL DECIMAL(10, 2) NOT NULL,
FOREIGN KEY (id_prod_cliente) REFERENCES PRODUTOS_CLIENTES(id_prod_cliente),
FOREIGN KEY (id_cliente) REFERENCES CLIENTES(id_cliente)
);

CREATE TABLE IMG_PRODUTOS_BRECHÓ (
ID_IMG INT PRIMARY KEY AUTO_INCREMENT,
ID_PROD_BRECHO INT NOT NULL,
URL_IMG VARCHAR(255) NOT NULL,
FOREIGN KEY (id_prod_brecho) REFERENCES PRODUTOS_BRECHO(id_prod_brecho)
);

CREATE TABLE IMG_PRODUTOS_CLIENTES (
ID_IMG INT PRIMARY KEY AUTO_INCREMENT,
ID_PROD_CLIENTE INT NOT NULL,
URL_IMG VARCHAR(255) NOT NULL,
FOREIGN KEY (id_prod_cliente) REFERENCES PRODUTOS_CLIENTES(id_prod_cliente)
);

CREATE TABLE CARRINHO_BRECHOS (
ID_CARRINHO INT PRIMARY KEY AUTO_INCREMENT,
ID_CLIENTE INT NOT NULL,
ID_PROD_BRECHO INT NOT NULL,
QUANTIDADE INT NOT NULL,
DATA_ADICAO DATETIME DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (id_cliente) REFERENCES CLIENTES(id_cliente),
FOREIGN KEY (id_prod_brecho) REFERENCES PRODUTOS_BRECHOS(id_prod_brecho)
);

CREATE TABLE CARRINHO_CLIENTES (
ID_CARRINHO INT PRIMARY KEY AUTO_INCREMENT,
ID_CLIENTE INT NOT NULL,
ID_PROD_CLIENTE INT NOT NULL,
QUANTIDADE INT NOT NULL,
DATA_ADICAO DATETIME DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (id_cliente) REFERENCES CLIENTES(id_cliente),
FOREIGN KEY (id_prod_cliente) REFERENCES PRODUTOS_CLIENTES(id_prod_cliente)
);

CREATE TABLE FAVORITOS (
ID_FAVORITO INT PRIMARY KEY AUTO_INCREMENT,
ID_CLIENTE INT NOT NULL,
ID_PROD_BRECHO INT,
ID_PROD_CLIENTE INT,
ID_BRECHO INT,
TIPO_FAVORITO ENUM('peca_brecho', 'peca_cliente', 'brecho') NOT NULL,
DATA_FAVORITO DATETIME DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (id_cliente) REFERENCES CLIENTES(id_cliente),
FOREIGN KEY (id_prod_brecho) REFERENCES PRODUTOS_BRECHOS(id_prod_brecho),
FOREIGN KEY (id_prod_cliente) REFERENCES PRODUTOS_CLIENTES(id_prod_cliente),
FOREIGN KEY (id_brecho) REFERENCES BRECHOS(id_brecho)
);

CREATE TABLE CARTOES (
ID_CARTAO INT PRIMARY KEY AUTO_INCREMENT,
ID_CLIENTE INT NOT NULL,
NUMERO_CARTAO VARCHAR(16) NOT NULL,
NOME_TITULAR VARCHAR(100) NOT NULL,
VALIDADE DATE NOT NULL,
CVV CHAR(3) NOT NULL,
FOREIGN KEY (id_cliente) REFERENCES CLIENTES(id_cliente)
);

CREATE TABLE AVALIACOES_BRECHO (
ID_AVALIACAO INT PRIMARY KEY AUTO_INCREMENT,
ID_BRECHO INT NOT NULL,
ID_CLIENTE INT NOT NULL,
NOTA INT CHECK (NOTA >= 1 AND NOTA <= 5),
COMENTARIO VARCHAR(500),
DATA_AVALIACAO DATETIME DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (id_brecho) REFERENCES BRECHOS(id_brecho),
FOREIGN KEY (id_cliente) REFERENCES CLIENTES(id_cliente)
);

CREATE TABLE SEGUIDORES (
ID_CLIENTE INT NOT NULL,
ID_BRECHO INT NOT NULL,
DATA_SEGUIMENTO DATETIME DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id_cliente, id_brecho),
FOREIGN KEY (id_cliente) REFERENCES CLIENTES(id_cliente),
FOREIGN KEY (id_brecho) REFERENCES BRECHOS(id_brecho)
);

CREATE TABLE ARTIGOS_BLOG (
ID_ARTIGO INT PRIMARY KEY AUTO_INCREMENT,
ID_AUTOR INT NOT NULL,
TITULO VARCHAR(255) NOT NULL,
CONTEUDO TEXT NOT NULL,
DATA_PUBLICACAO DATETIME DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (id_autor) REFERENCES USUARIOS(id_usuario)
);

CREATE TABLE CATEGORIAS_BLOG (
ID_CATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
NOME_CATEGORIA VARCHAR(100) NOT NULL
);

CREATE TABLE ARTIGOS_CATEGORIAS (
ID_ARTIGO INT NOT NULL,
ID_CATEGORIA INT NOT NULL,
PRIMARY KEY (id_artigo, id_categoria),
FOREIGN KEY (id_artigo) REFERENCES ARTIGOS_BLOG(id_artigo),
FOREIGN KEY (id_categoria) REFERENCES CATEGORIAS_BLOG(id_categoria)
);



    
    
    
    
    